# config.py

ENV_NAME = "LunarLanderContinuous-v3"

SEED = 42

# Training
SAC_TOTAL_STEPS = 300_000
PPO_TOTAL_STEPS = 1_000_000

# SAC hyperparameters
GAMMA = 0.99
TAU = 0.005
ACTOR_LR = 3e-4
CRITIC_LR = 3e-4
ALPHA_LR = 3e-4
BUFFER_SIZE = 1_000_000
BATCH_SIZE = 256
HIDDEN_DIM = 256
START_STEPS = 10_000
UPDATE_AFTER = 1_000
UPDATE_EVERY = 1
TARGET_UPDATE_INTERVAL = 1

# Evaluation
EVAL_EPISODES = 5
MAX_EPISODE_STEPS = 1000

# Paths
SAC_MODEL_DIR = "models/custom_sac"
PPO_MODEL_DIR = "models/ppo"
SAC_LOG_DIR = "logs/custom_sac"
PPO_LOG_DIR = "logs/ppo"
PLOTS_DIR = "plots"
VIDEOS_DIR = "videos"

# PPO hyperparameters
PPO_LEARNING_RATE = 3e-4
PPO_N_STEPS = 2048
PPO_BATCH_SIZE = 64
PPO_N_EPOCHS = 10
PPO_GAMMA = 0.99
PPO_GAE_LAMBDA = 0.95
PPO_CLIP_RANGE = 0.2


# Custom PPO hyperparameters
CUSTOM_PPO_TOTAL_STEPS = 1_000_000
CUSTOM_PPO_ROLLOUT_STEPS = 2048
CUSTOM_PPO_UPDATE_EPOCHS = 10
CUSTOM_PPO_BATCH_SIZE = 64
CUSTOM_PPO_LEARNING_RATE = 3e-4
CUSTOM_PPO_GAMMA = 0.99
CUSTOM_PPO_GAE_LAMBDA = 0.95
CUSTOM_PPO_CLIP_RANGE = 0.2
CUSTOM_PPO_VALUE_COEF = 0.5
CUSTOM_PPO_ENTROPY_COEF = 0.01
CUSTOM_PPO_MAX_GRAD_NORM = 0.5

CUSTOM_PPO_MODEL_DIR = "models/custom_ppo"
CUSTOM_PPO_LOG_DIR = "logs/custom_ppo"